package com.questionnaire.ssm.module.global.mapper;

import com.questionnaire.ssm.module.global.pojo.MappingRolePermission;
import com.questionnaire.ssm.module.global.pojo.MappingRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MappingRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int countByExample(MappingRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int deleteByExample(MappingRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int insert(MappingRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(MappingRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    List<MappingRolePermission> selectByExample(MappingRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    MappingRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MappingRolePermission record, @Param("example") MappingRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MappingRolePermission record, @Param("example") MappingRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MappingRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MappingRolePermission record);
}