package com.questionnaire.ssm.module.global.mapper;

import com.questionnaire.ssm.module.global.pojo.RecordLogin;
import com.questionnaire.ssm.module.global.pojo.RecordLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int countByExample(RecordLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int deleteByExample(RecordLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int insert(RecordLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int insertSelective(RecordLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    List<RecordLogin> selectByExample(RecordLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    RecordLogin selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecordLogin record, @Param("example") RecordLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecordLogin record, @Param("example") RecordLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecordLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecordLogin record);
}