package com.questionnaire.ssm.module.global.pojo;

import java.util.Date;

public class RecordLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_login.record_id
     *
     * @mbggenerated
     */
    private Long recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_login.user_tel
     *
     * @mbggenerated
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_login.last_login_date
     *
     * @mbggenerated
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_login.last_login_ip
     *
     * @mbggenerated
     */
    private String lastLoginIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_login.record_id
     *
     * @return the value of record_login.record_id
     *
     * @mbggenerated
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_login.record_id
     *
     * @param recordId the value for record_login.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_login.user_tel
     *
     * @return the value of record_login.user_tel
     *
     * @mbggenerated
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_login.user_tel
     *
     * @param userTel the value for record_login.user_tel
     *
     * @mbggenerated
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_login.last_login_date
     *
     * @return the value of record_login.last_login_date
     *
     * @mbggenerated
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_login.last_login_date
     *
     * @param lastLoginDate the value for record_login.last_login_date
     *
     * @mbggenerated
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_login.last_login_ip
     *
     * @return the value of record_login.last_login_ip
     *
     * @mbggenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_login.last_login_ip
     *
     * @param lastLoginIp the value for record_login.last_login_ip
     *
     * @mbggenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }
}