package com.questionnaire.ssm.module.notice.mapper;

import com.questionnaire.ssm.module.notice.pojo.MappingNoticeUnit;
import com.questionnaire.ssm.module.generated.pojo.MappingNoticeUnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MappingNoticeUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int countByExample(MappingNoticeUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int deleteByExample(MappingNoticeUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int insert(MappingNoticeUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int insertSelective(MappingNoticeUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    List<MappingNoticeUnit> selectByExample(MappingNoticeUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    MappingNoticeUnit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MappingNoticeUnit record, @Param("example") MappingNoticeUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MappingNoticeUnit record, @Param("example") MappingNoticeUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MappingNoticeUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MappingNoticeUnit record);
}