package com.questionnaire.ssm.module.notice.mapper;

import com.questionnaire.ssm.module.notice.pojo.MappingNoticeRole;
import com.questionnaire.ssm.module.generated.pojo.MappingNoticeRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MappingNoticeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int countByExample(MappingNoticeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int deleteByExample(MappingNoticeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int insert(MappingNoticeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int insertSelective(MappingNoticeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    List<MappingNoticeRole> selectByExample(MappingNoticeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    MappingNoticeRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MappingNoticeRole record, @Param("example") MappingNoticeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MappingNoticeRole record, @Param("example") MappingNoticeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MappingNoticeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapping_notice_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MappingNoticeRole record);
}