package com.questionnaire.ssm.module.notice.mapper;

import com.questionnaire.ssm.module.notice.pojo.RecordOperateNotice;
import com.questionnaire.ssm.module.generated.pojo.RecordOperateNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordOperateNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int countByExample(RecordOperateNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int deleteByExample(RecordOperateNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int insert(RecordOperateNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int insertSelective(RecordOperateNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    List<RecordOperateNotice> selectByExample(RecordOperateNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    RecordOperateNotice selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecordOperateNotice record, @Param("example") RecordOperateNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecordOperateNotice record, @Param("example") RecordOperateNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecordOperateNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_operate_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecordOperateNotice record);
}